package UI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author miskara
 */
import javax.swing.*;
import database.*;
import java.awt.Label;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import projekti.*;

public class ProjektiUI extends JFrame implements ChangeListener {

    Kyselyt k = new Kyselyt();

    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
        } catch (NumberFormatException e) {
            return false;
        }
        return true;
    }
    public void sliderTest(int aineet){
        JSlider[] j = new JSlider[6];
        j[0] = jSlider2;
        j[1] = jSlider3;
        j[2] = jSlider4;
        j[3] = jSlider5;
        JLabel[] l = new JLabel[6];
        l[0]=jLabel9;
        l[1]=jLabel10;
        l[2]=jLabel11;
        l[3]=jLabel12;
        Label[] l1 = new Label[6];
        l1[0]=label11;
        l1[1]=label8;
        l1[2]=label9;
        l1[3]=label10;
        for (int i=0; i<aineet; i++){
            j[i].setVisible(true);
            l[i].setVisible(true);
            l1[i].setVisible(true);
            for(int u=3;u>i;u-- ){
                j[u].setVisible(false);
                l[u].setVisible(false);
                l1[u].setVisible(false);
            }
        }
    }
    
        public boolean isDouble(String s) {
        try {
            Double.parseDouble(s);
        } catch (NumberFormatException e) {
            return false;
        }
        return true;
    }

    public final void asetatiedot() {
        k.avaaDB();
        drinkList.removeAll();
        for (int i = 0; i < k.Drinkkilista.size(); i++) {
            drinkList.add(k.Drinkkilista.get(i).getNimi());
        }
        aineList.removeAll();
        for (int i = 0; i < k.ainelista.size(); i++) {
            aineList.add(k.ainelista.get(i).getNimi());
        }
        list2.removeAll();
        for (int i = 0; i < k.ainelista.size(); i++) {
            list2.add(k.ainelista.get(i).getNimi());
        }
    }
        public final void setAinesosat() {
        k.avaaDB();

        aineList1.removeAll();
        for (int i = 0; i < k.ainelista.size(); i++) {
            aineList1.add(k.ainelista.get(i).getNimi());
        }
    }
        public final void sliderit(){
        jSlider2.setVisible(false);
        jSlider2.setValue(10);
        jSlider2.setPaintLabels(true);
        jSlider2.setPaintTicks(true);
        jSlider2.setSnapToTicks(true);
        jSlider2.addChangeListener(this);
        jSlider3.setVisible(false);
        jSlider3.setValue(10);
        jSlider3.setPaintLabels(true);
        jSlider3.setPaintTicks(true);
        jSlider3.setSnapToTicks(true);
        jSlider3.addChangeListener(this);
        jSlider4.setVisible(false);
        jSlider4.setValue(10);
        jSlider4.setPaintLabels(true);
        jSlider4.setPaintTicks(true);
        jSlider4.setSnapToTicks(true);
        jSlider4.addChangeListener(this);
        jSlider5.setVisible(false);
        jSlider5.setValue(10);
        jSlider5.setPaintLabels(true);
        jSlider5.setPaintTicks(true);
        jSlider5.setSnapToTicks(true);
        jSlider5.addChangeListener(this);
        label8.setVisible(false);
        label8.setText("");
        label9.setVisible(false);
        label9.setText("");
        label10.setVisible(false);
        label10.setText("");
        label11.setVisible(false);
        label11.setText("");
        lisää.setVisible(false);
        jLabel9.setText("");
        jLabel9.setVisible(false);
        jLabel10.setText("");
        jLabel10.setVisible(false);
        jLabel11.setText("");
        jLabel11.setVisible(false);
        jLabel12.setText("");
        jLabel12.setVisible(false);
        }

    /**
     * Creates new form ProjektiUI
     */
    public ProjektiUI() {
        initComponents();
        asetatiedot();
        sliderit();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drinkkiLisää = new javax.swing.JDialog();
        lisääLabel = new javax.swing.JLabel();
        lisää = new javax.swing.JButton();
        drinkinNimi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        aineList1 = new java.awt.List();
        label1 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        label11 = new java.awt.Label();
        jSlider2 = new javax.swing.JSlider();
        jSlider3 = new javax.swing.JSlider();
        jSlider4 = new javax.swing.JSlider();
        jSlider5 = new javax.swing.JSlider();
        Valitse = new javax.swing.JButton();
        Hinta1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ainesosaLisää = new javax.swing.JDialog();
        AineLisää = new javax.swing.JLabel();
        ainesosan_nimi = new javax.swing.JTextField();
        annaNimi = new javax.swing.JLabel();
        lisää_ainesosa = new javax.swing.JButton();
        määrä = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        list1 = new java.awt.List();
        Tilaus = new javax.swing.JFrame();
        jLabel7 = new javax.swing.JLabel();
        varastoonliäysButton = new javax.swing.JButton();
        list2 = new java.awt.List();
        amount = new java.awt.TextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        drinkkiLista = new javax.swing.JLabel();
        lisääAinesosa = new javax.swing.JButton();
        lisääDrinkki = new javax.swing.JButton();
        ostaDrinkki = new javax.swing.JButton();
        tilaaAinesosia = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        drinkList = new java.awt.List();
        aineList = new java.awt.List();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();

        drinkkiLisää.setAlwaysOnTop(true);
        drinkkiLisää.setBounds(new java.awt.Rectangle(0, 0, 800, 500));
        drinkkiLisää.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lisääLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lisääLabel.setText("Lisää Drinkki");

        lisää.setText("Lisää");
        lisää.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lisääActionPerformed(evt);
            }
        });

        drinkinNimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkinNimiActionPerformed(evt);
            }
        });

        jLabel5.setText("Syötä drinkin nimi");

        aineList1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aineList1ActionPerformed(evt);
            }
        });

        label1.setText("Määrä");

        label11.setName(""); // NOI18N

        jSlider2.setMaximum(20);
        jSlider2.setMinorTickSpacing(1);
        jSlider2.setPaintLabels(true);
        jSlider2.setPaintTicks(true);
        jSlider2.setValue(10);
        jSlider2.setAutoscrolls(true);
        jSlider2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jSlider3.setMaximum(20);
        jSlider3.setMinorTickSpacing(1);
        jSlider3.setPaintLabels(true);
        jSlider3.setPaintTicks(true);
        jSlider3.setValue(10);

        jSlider4.setMaximum(20);
        jSlider4.setMinorTickSpacing(1);
        jSlider4.setPaintLabels(true);
        jSlider4.setPaintTicks(true);
        jSlider4.setValue(10);

        jSlider5.setMaximum(20);
        jSlider5.setMinorTickSpacing(1);
        jSlider5.setPaintLabels(true);
        jSlider5.setPaintTicks(true);
        jSlider5.setValue(10);

        Valitse.setText("Valitse");
        Valitse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValitseActionPerformed(evt);
            }
        });

        Hinta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hinta1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Hinta");

        javax.swing.GroupLayout drinkkiLisääLayout = new javax.swing.GroupLayout(drinkkiLisää.getContentPane());
        drinkkiLisää.getContentPane().setLayout(drinkkiLisääLayout);
        drinkkiLisääLayout.setHorizontalGroup(
            drinkkiLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, drinkkiLisääLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(drinkkiLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, drinkkiLisääLayout.createSequentialGroup()
                        .addGroup(drinkkiLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(drinkkiLisääLayout.createSequentialGroup()
                                .addComponent(Valitse, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lisää, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(drinkkiLisääLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(drinkkiLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(drinkkiLisääLayout.createSequentialGroup()
                                        .addGroup(drinkkiLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(drinkkiLisääLayout.createSequentialGroup()
                                                .addGroup(drinkkiLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(drinkinNimi, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel8))
                                                .addGap(46, 46, 46))
                                            .addGroup(drinkkiLisääLayout.createSequentialGroup()
                                                .addGroup(drinkkiLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(Hinta1, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(aineList1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(drinkkiLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(drinkkiLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(drinkkiLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(label11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(label8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(label9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(label10, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(drinkkiLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSlider5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, drinkkiLisääLayout.createSequentialGroup()
                        .addGap(0, 206, Short.MAX_VALUE)
                        .addComponent(lisääLabel)
                        .addGap(163, 163, 163))))
        );
        drinkkiLisääLayout.setVerticalGroup(
            drinkkiLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drinkkiLisääLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lisääLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(drinkkiLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(drinkinNimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(drinkkiLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(drinkkiLisääLayout.createSequentialGroup()
                        .addGroup(drinkkiLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(drinkkiLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(drinkkiLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(31, 31, 31)
                        .addGroup(drinkkiLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addComponent(aineList1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(drinkkiLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(drinkkiLisääLayout.createSequentialGroup()
                        .addGroup(drinkkiLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSlider5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(drinkkiLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lisää, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Valitse, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(drinkkiLisääLayout.createSequentialGroup()
                        .addGroup(drinkkiLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Hinta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        ainesosaLisää.setBounds(new java.awt.Rectangle(0, 0, 600, 300));
        ainesosaLisää.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        AineLisää.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        AineLisää.setText("Lisää Ainesosa");

        ainesosan_nimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ainesosan_nimiActionPerformed(evt);
            }
        });

        annaNimi.setText("Ainesosan nimi");

        lisää_ainesosa.setText("Lisää");
        lisää_ainesosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lisää_ainesosaActionPerformed(evt);
            }
        });

        jLabel3.setText("Kuinka paljon lisätään varastoon (cl)");

        javax.swing.GroupLayout ainesosaLisääLayout = new javax.swing.GroupLayout(ainesosaLisää.getContentPane());
        ainesosaLisää.getContentPane().setLayout(ainesosaLisääLayout);
        ainesosaLisääLayout.setHorizontalGroup(
            ainesosaLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ainesosaLisääLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(ainesosaLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ainesosan_nimi, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(annaNimi))
                .addGap(112, 112, 112)
                .addGroup(ainesosaLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(määrä))
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ainesosaLisääLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ainesosaLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ainesosaLisääLayout.createSequentialGroup()
                        .addComponent(AineLisää)
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ainesosaLisääLayout.createSequentialGroup()
                        .addComponent(lisää_ainesosa, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        ainesosaLisääLayout.setVerticalGroup(
            ainesosaLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ainesosaLisääLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AineLisää)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ainesosaLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ainesosaLisääLayout.createSequentialGroup()
                        .addComponent(annaNimi)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ainesosaLisääLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(ainesosaLisääLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ainesosan_nimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(määrä, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lisää_ainesosa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Tilaus.setBounds(new java.awt.Rectangle(0, 0, 600, 600));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel7.setText("Lisää Varastoon");

        varastoonliäysButton.setText("Tilaa");
        varastoonliäysButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varastoonliäysButtonActionPerformed(evt);
            }
        });

        list2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list1ActionPerformed(evt);
            }
        });

        amount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountActionPerformed(evt);
            }
        });

        jLabel4.setText("Ainesosat");

        jLabel6.setText("Lisättävä määrä");

        javax.swing.GroupLayout TilausLayout = new javax.swing.GroupLayout(Tilaus.getContentPane());
        Tilaus.getContentPane().setLayout(TilausLayout);
        TilausLayout.setHorizontalGroup(
            TilausLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TilausLayout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(189, 189, 189))
            .addGroup(TilausLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(TilausLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TilausLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(TilausLayout.createSequentialGroup()
                        .addComponent(list2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(TilausLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TilausLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(varastoonliäysButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(TilausLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(TilausLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        TilausLayout.setVerticalGroup(
            TilausLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TilausLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addGroup(TilausLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TilausLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(list2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 144, Short.MAX_VALUE))
                    .addGroup(TilausLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(varastoonliäysButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        drinkkiLista.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        drinkkiLista.setText("Drinkkilista");

        lisääAinesosa.setText("Lisää ainesosa");
        lisääAinesosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lisääAinesosaActionPerformed(evt);
            }
        });

        lisääDrinkki.setText("Lisää Drinkki");
        lisääDrinkki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lisääDrinkkiActionPerformed(evt);
            }
        });

        ostaDrinkki.setText("Osta");
        ostaDrinkki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ostaDrinkkiActionPerformed(evt);
            }
        });

        tilaaAinesosia.setText("Tilaa Ainesosia");
        tilaaAinesosia.setMargin(new java.awt.Insets(0, 14, 0, 14));
        tilaaAinesosia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tilaaAinesosiaActionPerformed(evt);
            }
        });

        jLabel1.setText("Drinkit");

        jLabel2.setText("Ainesosat");

        drinkList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkListActionPerformed(evt);
            }
        });

        aineList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aineListActionPerformed(evt);
            }
        });

        label2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        label2.setText("Valitse Drinkki");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(drinkkiLista, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(drinkList, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(aineList, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(tilaaAinesosia, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(ostaDrinkki, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lisääAinesosa, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lisääDrinkki, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(label3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(drinkkiLista, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lisääDrinkki, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lisääAinesosa, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tilaaAinesosia, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ostaDrinkki, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(aineList, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                    .addComponent(drinkList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lisääAinesosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lisääAinesosaActionPerformed
        ainesosaLisää.setVisible(true);
        ainesosan_nimi.grabFocus();
    }//GEN-LAST:event_lisääAinesosaActionPerformed

    private void lisääDrinkkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lisääDrinkkiActionPerformed
        drinkkiLisää.setVisible(true);
        sliderit();

        setAinesosat();
        aineList1.setMultipleMode(true);
        
    }//GEN-LAST:event_lisääDrinkkiActionPerformed

    private void drinkinNimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkinNimiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drinkinNimiActionPerformed

    private void lisääActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lisääActionPerformed
       if(isDouble(Hinta1.getText())==false){
           Hinta1.setText("Syötä oikea arvo!");
       }
       else{
        int[] aineet = aineList1.getSelectedIndexes();
        int[] maarat = new int[6];
        JSlider[] j = new JSlider[6];
        j[0] = jSlider2;
        j[1] = jSlider3;
        j[2] = jSlider4;
        j[3] = jSlider5;
        
        for(int i = 0; i < aineet.length; i++){
        maarat[i] = j[i].getValue();
                }
        
        k.lisääDrinkki(drinkinNimi.getText(), Double.parseDouble(Hinta1.getText()), aineet,maarat);
        drinkinNimi.setText("");
        aineList1.clear();
        drinkkiLisää.hide();
        asetatiedot();
        jSlider2.setVisible(false);
        jSlider3.setVisible(false);
        jSlider4.setVisible(false);
        jSlider5.setVisible(false);
        label8.setVisible(false);
        label9.setVisible(false);
        label10.setVisible(false);
        label11.setVisible(false);
        //lisää.setVisible(false);
       }
    }//GEN-LAST:event_lisääActionPerformed

    private void ainesosan_nimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ainesosan_nimiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ainesosan_nimiActionPerformed

    private void lisää_ainesosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lisää_ainesosaActionPerformed
        
        if (ainesosan_nimi.getText()==null || isInteger(määrä.getText()) == false) {
            ainesosan_nimi.grabFocus();
            määrä.setText("");
        } else {
            k.lisääAinesosa(ainesosan_nimi.getText(), Integer.parseInt(määrä.getText()));
            ainesosan_nimi.setText("");
            määrä.setText("");
            ainesosaLisää.hide();
            asetatiedot();
        }
    
    }//GEN-LAST:event_lisää_ainesosaActionPerformed

    private void ostaDrinkkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ostaDrinkkiActionPerformed
        k.ostaJuoma(drinkList.getSelectedIndex());
    }//GEN-LAST:event_ostaDrinkkiActionPerformed

    private void drinkListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkListActionPerformed
        aineList.deselect(aineList.getSelectedIndex());
                String[] s = new String[6];
        s = k.naytaAinesosat(drinkList.getSelectedIndex());

        label2.setText(drinkList.getSelectedItem());

        label3.setText(s[0]);
        label4.setText(s[1]);
        label5.setText(s[2]);
        label6.setText(s[3]);
    }//GEN-LAST:event_drinkListActionPerformed

    private void aineListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aineListActionPerformed
        drinkList.deselect(drinkList.getSelectedIndex());
    }//GEN-LAST:event_aineListActionPerformed

    private void tilaaAinesosiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tilaaAinesosiaActionPerformed
        Tilaus.setVisible(true);

        
    }//GEN-LAST:event_tilaaAinesosiaActionPerformed

    private void amountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountActionPerformed

    private void list1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_list1ActionPerformed

    private void varastoonliäysButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varastoonliäysButtonActionPerformed
             if (list2.getSelectedItem()==null|| isInteger(amount.getText())==false) {
             amount.setText("Syötä tähän kokonaisluku");
        } else {
            k.tilaus(list2.getSelectedItem(), Integer.parseInt(amount.getText()));
            list2.deselect(list2.getSelectedIndex());
            amount.setText("");
            Tilaus.setVisible(false);
            asetatiedot();
            
        }
    }//GEN-LAST:event_varastoonliäysButtonActionPerformed

    private void ValitseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValitseActionPerformed
                String[] aineet = aineList1.getSelectedItems();
                
        if (aineet.length > 0) {
            lisää.setVisible(true);
            //Valitse.setVisible(false);
            jSlider2.setVisible(true);
            label11.setText(aineet[0]);
            label11.setVisible(true);
            jLabel9.setVisible(true);
            label11.revalidate();
        }  if (aineet.length > 1) {
            jSlider3.setVisible(true);
            label8.setText(aineet[1]);
            label8.setVisible(true);
            jLabel10.setVisible(true);
            label8.revalidate();
        }  if (aineet.length > 2) {
            jSlider4.setVisible(true);
            label9.setText(aineet[2]);
            label9.setVisible(true);
            jLabel11.setVisible(true);
            label9.revalidate();
        }if (aineet.length > 3) {
            jSlider5.setVisible(true);
            label10.setText(aineet[3]);
            label10.setVisible(true);
            jLabel12.setVisible(true);
            label10.revalidate();
        }
        sliderTest(aineet.length);
    }//GEN-LAST:event_ValitseActionPerformed

    private void aineList1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aineList1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aineList1ActionPerformed

    private void Hinta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hinta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hinta1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjektiUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AineLisää;
    private javax.swing.JTextField Hinta1;
    private javax.swing.JFrame Tilaus;
    private javax.swing.JButton Valitse;
    private java.awt.List aineList;
    private java.awt.List aineList1;
    private javax.swing.JDialog ainesosaLisää;
    private javax.swing.JTextField ainesosan_nimi;
    private java.awt.TextField amount;
    private javax.swing.JLabel annaNimi;
    private java.awt.List drinkList;
    private javax.swing.JTextField drinkinNimi;
    private javax.swing.JLabel drinkkiLista;
    private javax.swing.JDialog drinkkiLisää;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JSlider jSlider4;
    private javax.swing.JSlider jSlider5;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.List list1;
    private java.awt.List list2;
    private javax.swing.JButton lisää;
    private javax.swing.JButton lisääAinesosa;
    private javax.swing.JButton lisääDrinkki;
    private javax.swing.JLabel lisääLabel;
    private javax.swing.JButton lisää_ainesosa;
    private javax.swing.JTextField määrä;
    private javax.swing.JButton ostaDrinkki;
    private javax.swing.JButton tilaaAinesosia;
    private javax.swing.JButton varastoonliäysButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void stateChanged(ChangeEvent ce) {
        jLabel9.setText((jSlider2.getValue()+"cl"));
        jLabel10.setText((jSlider3.getValue()+"cl"));
        jLabel11.setText((jSlider4.getValue()+"cl"));
        jLabel12.setText((jSlider5.getValue()+"cl"));
        
    }
}
